_test_script: &nodetest
  language: node_js
  script:
  - yarn lint
  - yarn test

jobs:
  include:
    - stage: test
      <<: *nodetest 
      node_js: '8'

    - stage: test
      <<: *nodetest 
      node_js: '9'

    - stage: publish
      language: ruby
      provider: script
      services:
        - docker
      script: ./travis/publish.sh
   
    - stage: "deploy to QA :rocket:"
      language: ruby
      services:
        - docker
      if: type IN (push) and branch in (master, feature/dockerfile)
      env:
        - GCLOUD_CLUSTER_ID=qa
        - GCLOUD_CLUSTER_ZONE=europe-west1-b
        - GCLOUD_PROJECT_ID=opla-200809
      install: ./travis/setup_k8s.sh
      script:
        - helm upgrade --install --debug front ./k8s --set front.image.tag=$TRAVIS_COMMIT -f k8s/values.yaml -f k8s/values.qa.yaml

stages:
- test
- publish
- "deploy to QA :rocket:"
