_test_script: &nodetest
  language: node_js
  script:
  - yarn lint
  - yarn test

jobs:
  include:
    - stage: test
      <<: *nodetest 
      node_js: '8'

    - stage: test
      <<: *nodetest 
      node_js: '9'

    - stage: publish
      language: ruby
      provider: script
      services:
        - docker
      script: ./travis/publish.sh
   
    - stage: "deploy to QA :rocket:"
      language: ruby
      services:
        - docker
      if: type IN (push) and branch in (master, feature/dockerfile)
      env:
        - GCLOUD_CLUSTER_ID=qa
        - GCLOUD_CLUSTER_ZONE=europe-west1-b
        - COMMIT_ID=$TRAVIS_COMMIT
        - K8S_ENV=qa
        #CLIENT_ID
        - secure: "aezc24cmaaqRWklrsdPz0rjeMbQRUAJZ7jtHOnCOohDvtODzPmtxRtNQ8bf02i8T2YL3K30NoyzokgPHdomYoFb8Zx8WIsJJ7IcParUScfFe8B68ZOKXYzbohKo5w1UKLLSyyIc189fY7enRrrtubN2Qmj5BEeyooZ3KfxIkVltXEfv4d0vE2ET4Z8M8UHpY/8iepGTLANYHPMp1Cul50odLFj8c/zjoDdtg0MPONk8cn6GIdX3/tRzIdw5hEtD/lWDM2tGLqC2Hwlx9RCtjYOa/C5g6eUrOy8RtSnSPqUJrc0EhLuTwDOnGrjVPpdtpVnv1+7yR3VbnNspyRRA7Wlaqd2goF6SMR8oiixoTQYitNx1u8+OtsfxrfgE51jAleeLcPZbE1IxKDBSpQllNDWgx8YrFNkVTznF2pDintf2lpiBuxzyXcPHnPh/QcMe3JtKsrUBciMKskC/EkgRipKzZn5iAvZ2uV55nDJ5b7RdkgXto74TShgQ5OIg269HCptWzH96BVxKkB2G6ee9ZXGLaixpteiUcYRM0KMM4Vn6Y54enLAb6nVrHe5REl7YU7viGlRqXIKMv/HGhXKmmQ7/rTzAGi5M0dR8jJh/suwv9six/bAgNd0JitqJpp7PsAEGRBSjCHtumNq3LZ9iwdcRnmsCfDCsSFXBh/zgBfnE="
        #CLIENT_SECRET
        - secure: "XFM1kXneaHgX3Rn9E6mfw5u8OfG6Id/Wrm/B6JaH5nWS3uSS7uBNgSTIZ4qmAfoUPtf7FCQUQ9J98qZx1r4KFtY9CB0KR2tB3vhozgZIXRg6auqBhCNKzmBmz8xfivMSgJgKoCGF9ABlGZTyzFZY6cLhGRF9CQQPxj2oKUYN001isRCq8yRldDZCnlO7hOgx2YG7YWsVxSQkbEtGEeeB+ugiJOOOTT3m0djZL4/FIxgD63hUJ44zpzruCZtBMnr7EEHy6rhbIPYD2CJwniOYLal0CCgQLB4QnjTeOoi2CoiGgL9HdAcUYHYSESgaOuzITsGL150Pz6EXFuqqErGDBw0+09XFzVnWLjQ1/olyYpV2O8TP574KuprsPtiaA+c+fKOokUECjV+E/7mKqIL8bQsqyJUMb2YXIMSeyKyvjQB+WeT3y5/Pc5iH0AewDelHC672P4qn1crMen3g/MOmG9BFyjUTpfJQMVteYJOl51pP7kK1GS5zUTgEeq/yTwZ24DWwEuReJNlKhzdEM2NSwTR7rdlvSeuJaIRuUtH1atQzljAXfLXyJLiczkQD0V1X5dvSFMskdt8VA7TWnOd8X1IppERsMtqkDcrgKdNACmXSFjfnsm7AbIMbUb3JswRi7bdorlXEgLqqtpZdeoK4TPjg+HnMMBYyb7BiDC2yl1o="
        #GCLOUD_PROJECT_ID
        - secure: "FVz4Y+6ryHbAG1y6K5TlWlD3VCFLcd4M4axoLAi/mbh6wHL/8FeAgGr/2BlCHhP/LIkmmNesmJptlFazmRwdWhTqhZQ8yEDNXpqpisL5CfnPL7VA+zTHMcKkpZn3fOKQ4C8GgkX5pfsYvOuEyMVgcUX0MtqI41oRZs5YSPiwsiVH3ohijxhCyq2zOVEdmj8g1+Sn3p6lMmS0PMa985Cj0gpjkAZwAYmSH3STsVqMpzzpf1LXWJ87BJUEW7yZPY0GJYc5tkvZmdUPTMCQuM5T5j6xR/cUeQuuAc0th2EH7exK41YpfZ57ciE/OhNhOL1RbaC6b8SJJO502g5FblwSA54SVgtVWoqv7WexAOTO/bV1z41gm70fHHMhtoQaj3/Qix/7c4s5Yn452CcRyKTsCddVhXI7iaxUMjgUR0THFSKx7IJ+r7aT/P++Sh33S1BxOh4yv7J+RyVfYVI4rbah+TS+wNXT0ZYCcL9Wt1aTPuFt4LQDLUpTaWrbXBMUyAAbzcu7rmiRBpHCyD2OmQ6Io/BcS7YrmnF5ri1soweSpaPXo5IDtb08PzI+aYvAe4XWrHg67nxu5doma71QOtkTuoAaNLA8+O8QyHls2tSklJ1/QyDaqtYhmdqfyY+Go2WDIEOB53LD0vAXH/rVKrU88xxQqAU/yrGWBuU1s6JDVkw="
        #API_DOMAIN
        - secure: "OpljbmCOM4al1K4GCfshwiV8iTwdqeqo/3meYH/FSTk59D75vCvyFe2YHh+zM9yvefHRt2AHQigTZJjTg8dZv44+SOLkNGlxSueprVVBjbyl59y3qFClKawLgQYfaVhS/JrfmCDVpwue3xBB7ZN0tBJgzaOzZGsr5hQ3EZWGT+jTw8tMcCjC7RkLBvAVPg/wub0pg9gcS2iYw0IeV7kRnT/u+JDgnnOA8tGi43RyTTo3RXr9e/qWzb5SlQT6GcuL3wtylma760hWh3M26rGKupqCdseEIZAZhdxq+IgMr2bumC2VQcbyxLBy4pMuvquL2Q3kzX/58JovD7TUIAKj3F4jFVKGIAky+T8ApKf8t+m6osaV71z4A3VClYdZz1XFbSnf/f0gc5VeSnEwkaUlYfXUHmItT0AWIiSaDqePrDFcjaBzuwYb/rkCt4Q3XrcCKdVm1o47tD1tKe3vI3MXCi9nn4ejRidLrXFagaJBJvhsQJeghsFnmTlS2Qr/aryudKr53FDZX/Stif80hRLD2FXiG0kjmeoKIbGiLKZ5dAnO18gHJ12rN6pnwSmr/cpDnCJSR8V30wkqNqT6BmP/73me3hCC07V4mYSo03qZgDRwBAq34a/HcSH4xKXAkZrEFS9vmQezT0LHOnAKJCO/OQzgCl7lnzGrXIto9vOHeh4="
        #FRONT_DOMAIN
        - secure: "KbvDLAeY+1BI5SUrHbyXudYIMxqeFt79iD/wWPtyb4n3G8XGY+3g+Iy1AYIKHsiFzeiM5+nkE7yJtTtua+Qt/Bx2ClwPDVa3MGunKfkKwa7Pf7RyQQeTi/GP+gPlrjNsMiP0lL9X2zVpdk7/2vpHpQm9g9vgHtFMDLcAviQL3cLzwM8RMQp0bH7mY/rQU81Q3J/2E2MlE78T+2qbxvATzynokcswyZgK5NMY1LYJVebNsJrMSCGi2x41KTc6bNtSW00RQiQWtRgqJjzOAKVyRv6RnlB7gLTGM7ssN7ZEULCugKVW24Pf1VQmjWnMUi+7S0NEt1Dk90CR/Pk0Ohe6jdzqk+cGTJln/FFt9XEn9yl8/1eeOFBiqePfScScHGXSS8SPJOTT2xkAOPs9gSEtYPMn5ckRD9GTO6qGL6O6NN+LD0pf9Yb0+JcY74pHc7rUgbIx+nPAdgVriZQtrfq390/rN5EUDSeBAT8xYYeUNuNpCbwNdvt+OCNjnkNQ5sGLR6uVI0j3kq2UDOVd8DWHmqfmKPB/Q/sbsP8gQ/AdjD9iIvh27iSmxbcVOc+6CwfhkVHv3fsBfhMaJF7Zu++xUXosAWdAXF93s4l9iQXzsBHAwb7X0JJ3ZCcoLnR9Pmcn8Q38mGHnUBjqpkPYN1NMuGtA/c72MIFt8+1W8k0rboQ="
      install: ./travis/setup_k8s.sh
      script: make deploy

stages:
- test
- publish
- "deploy to QA :rocket:"

env:
  global:
  #DOCKER_USER
  - secure: Gg9DGLKjP7jTxdPwZmzAFI0+dqzIC9Guh1URkDefc+YvHAcpCBBiP22eY3Nyf3oakNL2JSd+Zdwi83ruWGDMjH2KL5wWdPYqWj4PG/atNde6o/lc2S9EZZKqziC1J//FN2IWQyITvDMXlCs4idCu3KTdOttB40KfHHtax8zz/pTqBnmQqCRd6CLTN0sZLP1vt02ORFhiXufVvMtfngjYl7ZEQYn3JNGsj+TDjUswXtvZ97qYauARo01V8ql4uHLeapU0kkoDmRMTFmE5p8fiNPQOLHuH3iJNX5VOZilfI5/ljpgLy84Y+R238ehAhqBZ4bUiPHQrgBP3uADyR0d7Yi3Khw2TF8P60vBX0JqK0R0Be+FINaOIgQ/YxOa5ut2lhkTlRIIkvinl0cuY+nxyNJTfxevaQB4GKphyuhdcbj4QqCDPcu3qsBnAYMInqySmRAlZPvnQd6z0tV0aTKd+ICz7v1vcC1tbjaq/dyrZf9pqdReTs1YQgpPC7TY2oMCMHiIJAJZQXw+7OWJRFrWJhN7f2lmNmk8tmBMccoct2KaQ2jYUW/hJpMAy8F5vzoHEnlQfZUa+EL+6gaC+OTCxsbvL9RGEHvvvgomDtzreVq7GEbPXgk/88p+QOeFvUMDH/DzJwpoTRpwxL03DSjB4gN6tSYbQbELGkD14Ab9qy9Q=
  #DOCKER_PASS
  - secure: Uk3D7/n+vN6X4YjmVShiccyL9bynmkyL9fWuH5IHn5wGc3vNYfHM180aReVT2LSphRvyO1uWG0bzQ8MM8gkuTc6A/DsrjBaSgKVpuvEFwBwo3rt9ZSyGcPFu7YJCRqlHHhiMkYCP5gzQ9mShjSO/KduVAZ3ktSVRokr/e4sfCNxHexmUciU3Y00U/govAh8/G8vN51y57r5iU2kO+z8UcxmwNbc8BsAu6hOKLfLVc/xQyGYqoqGqjjfvO5tNsAySuhhkLDW5taHQOMfy/E4pzGguze+Z42FH1fEYXibZDHPp+0D65VzwUhVQba2lha+FYq2v/VQgjb04xWmeel1l7jDexmhAp1cwZJ1uxr6H94xcsb1Fckip8JOY4ObQRDZpwRU7SrdIuNRPBmGPhOfejhhkNSLlCWieYxK8xHdsLy1W6CR9SU8Z/lDmEqOV0jda/zsd8Yv6kwhPyj36jpx1HP+q1wanzyDpG4Eksryp7hF/5VKvzRTFZ5zhYCv0X4hfXL+pJaFwkbe0jDCOK3CusXpZfSOC/aQr8TkmHR3MRlcl6K1GRPkhbs/fXua3E2TWO8Wd5XT2xyZY/N92Tji491+LSxW8ApXnQZguo6cPDfuLZ52RfyZ6rfTJ29Ta2Bg9HmilsC3bWG5bLh6UmsUEIUqr9T5gYpozfFrJD9UBvtU=
