__steps:
  - run: &dockerauth
      command: echo "$DOCKER_PASS" | docker login -u "$DOCKER_USER" --password-stdin
  - run: &gcloudauth
      command: |
          echo ${GOOGLE_AUTH} > ${HOME}/gcp-key.json
          gcloud auth activate-service-account --key-file ${HOME}/gcp-key.json
          gcloud --quiet config set project ${GOOGLE_PROJECT_ID}
          gcloud auth configure-docker
  - run: &deploy
      name: deploy
      command: |
        gcloud container clusters get-credentials ${GCLOUD_CLUSTER_ID} --zone=${GOOGLE_COMPUTE_ZONE}
        helm init --service-account tiller --upgrade
        COMMIT_SHA=$CIRCLE_SHA1 myke preview
        COMMIT_SHA=$CIRCLE_SHA1 myke deploy
  - run: &notify0
      when: on_success
      command: TEST_RESULT=0 DOMAIN="$K8S_NAMESPACE.$DOMAIN" myke front/_circle_notify
  - run: &notify1
      when: on_fail
      command: TEST_RESULT=1 DOMAIN="$K8S_NAMESPACE.$DOMAIN" myke front/_circle_notify
  - run: &initsubmodules git submodule sync && git submodule update --init

version: 2
jobs:
  test:
    docker:
      - image: circleci/node:8
    steps:
      - checkout
      - run: *initsubmodules
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
        
      - run: yarn lint
      - run: yarn test
  
  build:
    docker: 
      - image: licarth/ci-cd:latest
    environment:
      K8S_ENV: qa
      K8S_NAMESPACE: qa-ce
      CLOUDSDK_CORE_DISABLE_PROMPTS: "1"
    steps:
      - checkout
      - run: *initsubmodules
      - setup_remote_docker
      - run: *dockerauth
      - run: myke front/ci_build --COMMIT_SHA=$CIRCLE_SHA1

  promote:
    docker: 
      - image: licarth/ci-cd:latest
    steps:
      - checkout
      - run: *initsubmodules
      - setup_remote_docker
      - run: *dockerauth
      - run: myke front/ci_promote --COMMIT_SHA=$CIRCLE_SHA1

  deploy_qa:
    docker:
      - image: licarth/ci-cd:latest
    environment:
      K8S_ENV: qa
      K8S_NAMESPACE: qa-ce
      GCLOUD_CLUSTER_ID: qa
    steps:
      - checkout
      - run: *initsubmodules
      - run: *gcloudauth
      - run: *deploy
      - run: *notify0
      - run: *notify1

  deploy_preprod:
    docker:
      - image: licarth/ci-cd:latest
    environment:
      K8S_ENV: preprod
      K8S_NAMESPACE: preprod-ce
      GCLOUD_CLUSTER_ID: qa
    steps:
      - checkout
      - run: *initsubmodules
      - run: *gcloudauth
      - run: *deploy
      - run: *notify0
      - run: *notify1

  deploy_prod:
    docker:
      - image: licarth/ci-cd:latest
    environment:
      K8S_ENV: prod
      K8S_NAMESPACE: prod-ce
      GCLOUD_CLUSTER_ID: qa

    steps:
      - checkout
      - run: *initsubmodules
      - run: *gcloudauth
      - run: *deploy
      - run: *notify0
      - run: *notify1

workflows:
  version: 2
  test_and_deploy:
    jobs:
      - test:
          filters:
            branches:
              ignore: gh-pages
            tags:
              only: /.*/
      - build
      - promote:
          requires:
            - build
            - test
          filters:
            branches:
              only: 
                - master
                - infra-update
      - deploy_qa:
          requires:
            - promote
      - deploy_preprod:
          requires:
            - promote
