---
apiVersion: v1
kind: ConfigMap
metadata:
  name: config
data:
  config.json: |-
      {
          "backend": {
              "api": {
                  "host": "{{ .Values.api.domain }}",
                  "path": "api/v1/",
                  "port": "443"
              },
              "auth": {
                  "clientId": "{{ .Values.auth.clientId }}",
                  "clientSecret": "{{ .Values.auth.secret }}",
                  "host": "{{ .Values.api.domain }}",
                  "path": "auth/",
                  "port": "443"
              },
              "secure": true
          }
      }
