---
kind: Service
apiVersion: v1
metadata:
  name: front
spec:
  selector:
    app: front
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: front
  labels:
    app: front
spec:
  replicas: 1
  selector:
    matchLabels:
      app: front
  template:
    metadata:
      labels:
        app: front
      metadata:
      annotations:
        checksum/configMap: {{ include (print $.Template.BasePath "/0-configmap.yaml") . | sha256sum }}
    spec:
      containers:
      - name: node
        image: "opla/front:{{ .Values.image.tag }}"
        ports:
        - containerPort: 80
        env:
        - name: PORT
          value: "80"
        - name: OPLA_API_DOMAIN
          value: "{{ .Values.api.domain }}"
        - name: OPLA_BACKEND_HOST
          value: "backend"
        - name: OPLA_FRONT_CLIENT_NAME
          value: "opla"
        - name: OPLA_BACKEND_PORT
          value: "80"
        volumeMounts:
        - mountPath: /src/config/config.json
          name: config
          subPath: config.json
      volumes:
      - configMap:
          name: config
        name: config
