---
apiVersion: v1
kind: ConfigMap
metadata:
  name: front-config
  namespace: {{ .Values.namespace }}
data:
  config.json: |-
      {
          "backend": {
              "api": {
                  "host": "{{ .Values.api.domain }}",
                  "path": "api/v1/",
                  "port": "{{ if eq .Values.tls true }}443{{else}}80{{end}}"
              },
              "auth": {
                  "clientId": "{{ .Values.auth.clientId }}",
                  "clientSecret": "{{ .Values.auth.secret }}",
                  "host": "{{ .Values.api.domain }}",
                  "path": "auth/",
                  "port": "{{ if eq .Values.tls true }}443{{else}}80{{end}}"
              },
              "secure": {{ if eq .Values.tls true }}true{{else}}false{{end}}
          }
      }
